### ISSUE TITLE
in_array() expects parameter 2 to be array, null given

### ISSUE THREAD

**Issue by JayteeNZ** [wilianx7/php-recurring#3]
In trait: DateMatch, line 52.

Happens because not setting as an array if the value is singular. Also, can't seem to get this package to generate a list of dates. Just receive an empty collection back (after I fix that error above).

**Comment by wilianx7** [comment]
I believe you have done an incorrect configuration. When the recurrence is weekly, even if you want to repeat only one day of the week, the `repeatIn` must be an array. That way, the error will not occur.
